site_name: rapporteur-helper
repo_url: https://github.com/jr2804/rapporteur-helper
site_url: https://jr2804.github.io/rapporteur-helper
site_description: ITU-T Rapporteur's status report generator
site_author: Jan Reimes
edit_uri: edit/main/docs/
repo_name: jr2804/rapporteur-helper
copyright: Maintained by <a href="https://jr2804.com">jr2804</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/rapporteur_helper"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jr2804/rapporteur-helper
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/rapporteur-helper

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
