[project]
name = "rapporteur-helper"
version = "0.1.0"
description = "ITU-T Rapporteur's status report generator"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "python-docx>=1.1.2",
    "requests>=2.32.3",
]
