[tasks.add-mcp-servers]
usage = '''
arg "<ai_agent>" help="AI assistant to use: claude, gemini, copilot, opencode, ... see: https://github.com/neondatabase/add-mcp"
'''
shell = "pwsh -NoProfile -Command"
run = [
    'cls',
    'bun x add-mcp -y -a {{usage.ai_agent}} -n cytoscnpy-mcp "cytoscnpy mcp-server"',
    'bun x add-mcp -y -a {{usage.ai_agent}} -n officecli "officecli mcp"',
]
